version: "3.8"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web_server
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
      - celery_beat

  db:
    image: postgres:14-alpine
    container_name: database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"

  redis:
    image: redis
    container_name: redis
    restart: always

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A sales_network worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A sales_network beat -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  postgres_data: